## numpy and pandas

In [3]:
import numpy as np
import pandas as pd

In [4]:
x = [1,2,3,4,4,3,5,6,8,5]
nx = np.array(x)

In [5]:
print(nx)

[1 2 3 4 4 3 5 6 8 5]


In [7]:
ny = np.array([[1,2,3],[4,5,6]])
ny

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(ny.shape)

(2, 3)


In [10]:
one = np.arange(1,100,.2)

In [11]:
print(one)

[ 1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6
  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6  5.8  6.   6.2  6.4
  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2
  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11.  11.2 11.4 11.6 11.8 12.
 12.2 12.4 12.6 12.8 13.  13.2 13.4 13.6 13.8 14.  14.2 14.4 14.6 14.8
 15.  15.2 15.4 15.6 15.8 16.  16.2 16.4 16.6 16.8 17.  17.2 17.4 17.6
 17.8 18.  18.2 18.4 18.6 18.8 19.  19.2 19.4 19.6 19.8 20.  20.2 20.4
 20.6 20.8 21.  21.2 21.4 21.6 21.8 22.  22.2 22.4 22.6 22.8 23.  23.2
 23.4 23.6 23.8 24.  24.2 24.4 24.6 24.8 25.  25.2 25.4 25.6 25.8 26.
 26.2 26.4 26.6 26.8 27.  27.2 27.4 27.6 27.8 28.  28.2 28.4 28.6 28.8
 29.  29.2 29.4 29.6 29.8 30.  30.2 30.4 30.6 30.8 31.  31.2 31.4 31.6
 31.8 32.  32.2 32.4 32.6 32.8 33.  33.2 33.4 33.6 33.8 34.  34.2 34.4
 34.6 34.8 35.  35.2 35.4 35.6 35.8 36.  36.2 36.4 36.6 36.8 37.  37.2
 37.4 37.6 37.8 38.  38.2 38.4 38.6 38.8 39.  39.2 39.4 39.6 39.8 40.
 40.2 40.

In [12]:
print(one.size)

495


In [15]:
two = np.linspace(1,100,200)

In [14]:
print(two)

[  1.           1.49748744   1.99497487   2.49246231   2.98994975
   3.48743719   3.98492462   4.48241206   4.9798995    5.47738693
   5.97487437   6.47236181   6.96984925   7.46733668   7.96482412
   8.46231156   8.95979899   9.45728643   9.95477387  10.45226131
  10.94974874  11.44723618  11.94472362  12.44221106  12.93969849
  13.43718593  13.93467337  14.4321608   14.92964824  15.42713568
  15.92462312  16.42211055  16.91959799  17.41708543  17.91457286
  18.4120603   18.90954774  19.40703518  19.90452261  20.40201005
  20.89949749  21.39698492  21.89447236  22.3919598   22.88944724
  23.38693467  23.88442211  24.38190955  24.87939698  25.37688442
  25.87437186  26.3718593   26.86934673  27.36683417  27.86432161
  28.36180905  28.85929648  29.35678392  29.85427136  30.35175879
  30.84924623  31.34673367  31.84422111  32.34170854  32.83919598
  33.33668342  33.83417085  34.33165829  34.82914573  35.32663317
  35.8241206   36.32160804  36.81909548  37.31658291  37.81407035
  38.31155

In [16]:
n3 = np.random.rand(100)

In [17]:
n3

array([0.56401448, 0.81333509, 0.31794491, 0.50882122, 0.8032063 ,
       0.34593393, 0.48312332, 0.39727879, 0.70672889, 0.25193545,
       0.27189453, 0.19000548, 0.66986297, 0.15652726, 0.91715121,
       0.63874124, 0.19298077, 0.46863911, 0.12814088, 0.2936068 ,
       0.8643507 , 0.85055356, 0.93857187, 0.32688328, 0.2764162 ,
       0.28745763, 0.15654321, 0.91631869, 0.59735786, 0.69231553,
       0.24543258, 0.25751531, 0.06144311, 0.94155022, 0.12321349,
       0.83214859, 0.45640065, 0.75666415, 0.0757207 , 0.36863049,
       0.62585892, 0.66038861, 0.79358565, 0.33945045, 0.36209352,
       0.39095723, 0.89033658, 0.04805391, 0.30061157, 0.27230763,
       0.19885713, 0.75126855, 0.76219576, 0.43902391, 0.61822192,
       0.56450833, 0.28028283, 0.15455515, 0.40916378, 0.91711825,
       0.85032224, 0.02748313, 0.27120984, 0.97304949, 0.21037461,
       0.13419078, 0.34602799, 0.188095  , 0.71809517, 0.05636411,
       0.42955647, 0.53938265, 0.25493818, 0.59750772, 0.99952

In [18]:
n4 = np.random.randint(1,10,100)

In [19]:
n4

array([2, 6, 8, 7, 8, 6, 7, 9, 2, 2, 3, 6, 3, 9, 4, 1, 6, 1, 3, 7, 1, 3,
       6, 2, 4, 7, 8, 8, 3, 4, 9, 1, 8, 4, 9, 4, 2, 9, 8, 4, 8, 1, 1, 8,
       8, 6, 1, 2, 6, 3, 4, 4, 8, 3, 2, 8, 3, 5, 8, 9, 1, 6, 8, 2, 7, 6,
       4, 2, 7, 1, 1, 3, 1, 6, 7, 3, 7, 2, 8, 1, 5, 1, 7, 9, 4, 1, 6, 6,
       9, 4, 3, 8, 2, 8, 2, 9, 6, 7, 1, 1])

In [20]:
n4.reshape((10,10))

array([[2, 6, 8, 7, 8, 6, 7, 9, 2, 2],
       [3, 6, 3, 9, 4, 1, 6, 1, 3, 7],
       [1, 3, 6, 2, 4, 7, 8, 8, 3, 4],
       [9, 1, 8, 4, 9, 4, 2, 9, 8, 4],
       [8, 1, 1, 8, 8, 6, 1, 2, 6, 3],
       [4, 4, 8, 3, 2, 8, 3, 5, 8, 9],
       [1, 6, 8, 2, 7, 6, 4, 2, 7, 1],
       [1, 3, 1, 6, 7, 3, 7, 2, 8, 1],
       [5, 1, 7, 9, 4, 1, 6, 6, 9, 4],
       [3, 8, 2, 8, 2, 9, 6, 7, 1, 1]])

In [22]:
n5 = n4.reshape((25,4))
n5

array([[2, 6, 8, 7],
       [8, 6, 7, 9],
       [2, 2, 3, 6],
       [3, 9, 4, 1],
       [6, 1, 3, 7],
       [1, 3, 6, 2],
       [4, 7, 8, 8],
       [3, 4, 9, 1],
       [8, 4, 9, 4],
       [2, 9, 8, 4],
       [8, 1, 1, 8],
       [8, 6, 1, 2],
       [6, 3, 4, 4],
       [8, 3, 2, 8],
       [3, 5, 8, 9],
       [1, 6, 8, 2],
       [7, 6, 4, 2],
       [7, 1, 1, 3],
       [1, 6, 7, 3],
       [7, 2, 8, 1],
       [5, 1, 7, 9],
       [4, 1, 6, 6],
       [9, 4, 3, 8],
       [2, 8, 2, 9],
       [6, 7, 1, 1]])

In [25]:
n1 = np.random.randint(1,10,(5,5))
n2 = np.random.randint(1,10,(5,5))
n1,n2

(array([[4, 8, 6, 9, 6],
        [6, 2, 9, 6, 8],
        [2, 9, 8, 6, 4],
        [4, 7, 9, 8, 6],
        [7, 5, 1, 8, 4]]),
 array([[4, 7, 9, 3, 5],
        [5, 7, 8, 8, 5],
        [9, 4, 7, 2, 6],
        [4, 3, 5, 1, 6],
        [7, 9, 5, 2, 3]]))

In [26]:
n1 + n2

array([[ 8, 15, 15, 12, 11],
       [11,  9, 17, 14, 13],
       [11, 13, 15,  8, 10],
       [ 8, 10, 14,  9, 12],
       [14, 14,  6, 10,  7]])

In [27]:
n1 - n2

array([[ 0,  1, -3,  6,  1],
       [ 1, -5,  1, -2,  3],
       [-7,  5,  1,  4, -2],
       [ 0,  4,  4,  7,  0],
       [ 0, -4, -4,  6,  1]])

In [28]:
n1 / n2

array([[1.        , 1.14285714, 0.66666667, 3.        , 1.2       ],
       [1.2       , 0.28571429, 1.125     , 0.75      , 1.6       ],
       [0.22222222, 2.25      , 1.14285714, 3.        , 0.66666667],
       [1.        , 2.33333333, 1.8       , 8.        , 1.        ],
       [1.        , 0.55555556, 0.2       , 4.        , 1.33333333]])

In [29]:
n2 ** n2

array([[      256,    823543, 387420489,        27,      3125],
       [     3125,    823543,  16777216,  16777216,      3125],
       [387420489,       256,    823543,         4,     46656],
       [      256,        27,      3125,         1,     46656],
       [   823543, 387420489,      3125,         4,        27]])

In [30]:
n1 ** 4

array([[ 256, 4096, 1296, 6561, 1296],
       [1296,   16, 6561, 1296, 4096],
       [  16, 6561, 4096, 1296,  256],
       [ 256, 2401, 6561, 4096, 1296],
       [2401,  625,    1, 4096,  256]], dtype=int32)

In [31]:
n1 + 10

array([[14, 18, 16, 19, 16],
       [16, 12, 19, 16, 18],
       [12, 19, 18, 16, 14],
       [14, 17, 19, 18, 16],
       [17, 15, 11, 18, 14]])

In [32]:
n1.dot(n2)

array([[188, 189, 217, 109, 168],
       [195, 182, 203,  74, 154],
       [177, 163, 196, 108, 151],
       [206, 191, 225, 106, 175],
       [122, 148, 170,  79, 126]])

In [34]:
n6 = np.random.randint(1,10,10)
n6

array([1, 6, 2, 1, 1, 6, 7, 3, 7, 3])

In [35]:
n1 * n2

array([[16, 56, 54, 27, 30],
       [30, 14, 72, 48, 40],
       [18, 36, 56, 12, 24],
       [16, 21, 45,  8, 36],
       [49, 45,  5, 16, 12]])

In [36]:
n6[0]

1

In [37]:
n6[1]

6

In [38]:
n6[-1]

3

In [39]:
n6[:5]

array([1, 6, 2, 1, 1])

In [40]:
n6[5:]

array([6, 7, 3, 7, 3])

- #1 dim * [start:stop:step]
- #2 dim * [rowstart:rowstop:rowstep,colstart:colstop:colstep]

In [41]:
n7 = np.random.randint(1,10,(3,3))

In [42]:
n7

array([[8, 7, 8],
       [8, 2, 3],
       [1, 2, 6]])